# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/j-f/cpp_indie_studio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/j-f/cpp_indie_studio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/j-f/cpp_indie_studio/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/j-f/cpp_indie_studio/CMakeFiles /home/j-f/cpp_indie_studio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/j-f/cpp_indie_studio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

#=============================================================================
# Target rules for targets named install

# Build rule for target.
install: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 install
.PHONY : install

# fast build rule for target.
install/fast:
	$(MAKE) -f CMakeFiles/install.dir/build.make CMakeFiles/install.dir/build
.PHONY : install/fast

src/Bomberman.o: src/Bomberman.cpp.o

.PHONY : src/Bomberman.o

# target to build an object file
src/Bomberman.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Bomberman.cpp.o
.PHONY : src/Bomberman.cpp.o

src/Bomberman.i: src/Bomberman.cpp.i

.PHONY : src/Bomberman.i

# target to preprocess a source file
src/Bomberman.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Bomberman.cpp.i
.PHONY : src/Bomberman.cpp.i

src/Bomberman.s: src/Bomberman.cpp.s

.PHONY : src/Bomberman.s

# target to generate assembly for a file
src/Bomberman.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Bomberman.cpp.s
.PHONY : src/Bomberman.cpp.s

src/Core.o: src/Core.cpp.o

.PHONY : src/Core.o

# target to build an object file
src/Core.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Core.cpp.o
.PHONY : src/Core.cpp.o

src/Core.i: src/Core.cpp.i

.PHONY : src/Core.i

# target to preprocess a source file
src/Core.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Core.cpp.i
.PHONY : src/Core.cpp.i

src/Core.s: src/Core.cpp.s

.PHONY : src/Core.s

# target to generate assembly for a file
src/Core.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Core.cpp.s
.PHONY : src/Core.cpp.s

src/DeviceReceiver.o: src/DeviceReceiver.cpp.o

.PHONY : src/DeviceReceiver.o

# target to build an object file
src/DeviceReceiver.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/DeviceReceiver.cpp.o
.PHONY : src/DeviceReceiver.cpp.o

src/DeviceReceiver.i: src/DeviceReceiver.cpp.i

.PHONY : src/DeviceReceiver.i

# target to preprocess a source file
src/DeviceReceiver.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/DeviceReceiver.cpp.i
.PHONY : src/DeviceReceiver.cpp.i

src/DeviceReceiver.s: src/DeviceReceiver.cpp.s

.PHONY : src/DeviceReceiver.s

# target to generate assembly for a file
src/DeviceReceiver.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/DeviceReceiver.cpp.s
.PHONY : src/DeviceReceiver.cpp.s

src/GenerateMap.o: src/GenerateMap.cpp.o

.PHONY : src/GenerateMap.o

# target to build an object file
src/GenerateMap.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/GenerateMap.cpp.o
.PHONY : src/GenerateMap.cpp.o

src/GenerateMap.i: src/GenerateMap.cpp.i

.PHONY : src/GenerateMap.i

# target to preprocess a source file
src/GenerateMap.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/GenerateMap.cpp.i
.PHONY : src/GenerateMap.cpp.i

src/GenerateMap.s: src/GenerateMap.cpp.s

.PHONY : src/GenerateMap.s

# target to generate assembly for a file
src/GenerateMap.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/GenerateMap.cpp.s
.PHONY : src/GenerateMap.cpp.s

src/Ia.o: src/Ia.cpp.o

.PHONY : src/Ia.o

# target to build an object file
src/Ia.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Ia.cpp.o
.PHONY : src/Ia.cpp.o

src/Ia.i: src/Ia.cpp.i

.PHONY : src/Ia.i

# target to preprocess a source file
src/Ia.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Ia.cpp.i
.PHONY : src/Ia.cpp.i

src/Ia.s: src/Ia.cpp.s

.PHONY : src/Ia.s

# target to generate assembly for a file
src/Ia.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Ia.cpp.s
.PHONY : src/Ia.cpp.s

src/IrrKlang.o: src/IrrKlang.cpp.o

.PHONY : src/IrrKlang.o

# target to build an object file
src/IrrKlang.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/IrrKlang.cpp.o
.PHONY : src/IrrKlang.cpp.o

src/IrrKlang.i: src/IrrKlang.cpp.i

.PHONY : src/IrrKlang.i

# target to preprocess a source file
src/IrrKlang.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/IrrKlang.cpp.i
.PHONY : src/IrrKlang.cpp.i

src/IrrKlang.s: src/IrrKlang.cpp.s

.PHONY : src/IrrKlang.s

# target to generate assembly for a file
src/IrrKlang.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/IrrKlang.cpp.s
.PHONY : src/IrrKlang.cpp.s

src/Irrlicht.o: src/Irrlicht.cpp.o

.PHONY : src/Irrlicht.o

# target to build an object file
src/Irrlicht.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Irrlicht.cpp.o
.PHONY : src/Irrlicht.cpp.o

src/Irrlicht.i: src/Irrlicht.cpp.i

.PHONY : src/Irrlicht.i

# target to preprocess a source file
src/Irrlicht.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Irrlicht.cpp.i
.PHONY : src/Irrlicht.cpp.i

src/Irrlicht.s: src/Irrlicht.cpp.s

.PHONY : src/Irrlicht.s

# target to generate assembly for a file
src/Irrlicht.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Irrlicht.cpp.s
.PHONY : src/Irrlicht.cpp.s

src/Menu.o: src/Menu.cpp.o

.PHONY : src/Menu.o

# target to build an object file
src/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu.cpp.o
.PHONY : src/Menu.cpp.o

src/Menu.i: src/Menu.cpp.i

.PHONY : src/Menu.i

# target to preprocess a source file
src/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu.cpp.i
.PHONY : src/Menu.cpp.i

src/Menu.s: src/Menu.cpp.s

.PHONY : src/Menu.s

# target to generate assembly for a file
src/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu.cpp.s
.PHONY : src/Menu.cpp.s

src/Params.o: src/Params.cpp.o

.PHONY : src/Params.o

# target to build an object file
src/Params.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Params.cpp.o
.PHONY : src/Params.cpp.o

src/Params.i: src/Params.cpp.i

.PHONY : src/Params.i

# target to preprocess a source file
src/Params.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Params.cpp.i
.PHONY : src/Params.cpp.i

src/Params.s: src/Params.cpp.s

.PHONY : src/Params.s

# target to generate assembly for a file
src/Params.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Params.cpp.s
.PHONY : src/Params.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Preroll.o: src/Preroll.cpp.o

.PHONY : src/Preroll.o

# target to build an object file
src/Preroll.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Preroll.cpp.o
.PHONY : src/Preroll.cpp.o

src/Preroll.i: src/Preroll.cpp.i

.PHONY : src/Preroll.i

# target to preprocess a source file
src/Preroll.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Preroll.cpp.i
.PHONY : src/Preroll.cpp.i

src/Preroll.s: src/Preroll.cpp.s

.PHONY : src/Preroll.s

# target to generate assembly for a file
src/Preroll.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Preroll.cpp.s
.PHONY : src/Preroll.cpp.s

src/Settings.o: src/Settings.cpp.o

.PHONY : src/Settings.o

# target to build an object file
src/Settings.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Settings.cpp.o
.PHONY : src/Settings.cpp.o

src/Settings.i: src/Settings.cpp.i

.PHONY : src/Settings.i

# target to preprocess a source file
src/Settings.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Settings.cpp.i
.PHONY : src/Settings.cpp.i

src/Settings.s: src/Settings.cpp.s

.PHONY : src/Settings.s

# target to generate assembly for a file
src/Settings.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Settings.cpp.s
.PHONY : src/Settings.cpp.s

src/Tools.o: src/Tools.cpp.o

.PHONY : src/Tools.o

# target to build an object file
src/Tools.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Tools.cpp.o
.PHONY : src/Tools.cpp.o

src/Tools.i: src/Tools.cpp.i

.PHONY : src/Tools.i

# target to preprocess a source file
src/Tools.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Tools.cpp.i
.PHONY : src/Tools.cpp.i

src/Tools.s: src/Tools.cpp.s

.PHONY : src/Tools.s

# target to generate assembly for a file
src/Tools.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Tools.cpp.s
.PHONY : src/Tools.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... bomberman"
	@echo "... install"
	@echo "... package"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Bomberman.o"
	@echo "... src/Bomberman.i"
	@echo "... src/Bomberman.s"
	@echo "... src/Core.o"
	@echo "... src/Core.i"
	@echo "... src/Core.s"
	@echo "... src/DeviceReceiver.o"
	@echo "... src/DeviceReceiver.i"
	@echo "... src/DeviceReceiver.s"
	@echo "... src/GenerateMap.o"
	@echo "... src/GenerateMap.i"
	@echo "... src/GenerateMap.s"
	@echo "... src/Ia.o"
	@echo "... src/Ia.i"
	@echo "... src/Ia.s"
	@echo "... src/IrrKlang.o"
	@echo "... src/IrrKlang.i"
	@echo "... src/IrrKlang.s"
	@echo "... src/Irrlicht.o"
	@echo "... src/Irrlicht.i"
	@echo "... src/Irrlicht.s"
	@echo "... src/Menu.o"
	@echo "... src/Menu.i"
	@echo "... src/Menu.s"
	@echo "... src/Params.o"
	@echo "... src/Params.i"
	@echo "... src/Params.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Preroll.o"
	@echo "... src/Preroll.i"
	@echo "... src/Preroll.s"
	@echo "... src/Settings.o"
	@echo "... src/Settings.i"
	@echo "... src/Settings.s"
	@echo "... src/Tools.o"
	@echo "... src/Tools.i"
	@echo "... src/Tools.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

